package com.example.patryk.memoryphotobook.BooksModel.managers

import android.content.Context
import android.graphics.BitmapFactory
import com.example.patryk.memoryphotobook.BooksModel.Frame
import com.example.patryk.memoryphotobook.R

class FrameManager(var context: Context) {
    var frameList : Array<Frame> = arrayOf(
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        )
    ,
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        ),
        Frame(
            BitmapFactory.decodeResource(
                context.resources,
                R.drawable.frame
            )
        )
    )
}